#/bin/bash

declare -a CONF_ARRAY
CONF_ARRAY=("1")

declare -a EXPT_ARRAY
EXPT_ARRAY=("1")
NUMEXPTS=${#CONF_ARRAY[@]}



for ((i=0;i<$NUMEXPTS;i++)); do

CONF=${CONF_ARRAY[i]}
EXPT=${EXPT_ARRAY[i]}

GAMMA="0.9"
MAXLEVEL="0"
MAXDELTA="0.1"
MAXHORIZONS="10"
EPSILON="0.001"
MAXSTAGES="15"
MAXTRIALS="100"
ITERATIVE_TRIALS="20"
SETSOFTRIAL="5"
SAMPLING_ERROR_BOUND="0.00001"
ALPHA="0.05"
PARTICLE_COUNT="1000"
BANDIT_CONSTANT="40"
TIME_BOUND="5000"
IS_FIRE_RANDOM="false"
IS_SUPP_RANDOM="true"
IS_AVGQ_ANODE="false"
IS_OPEN_SUPP="false"
IS_SINGLE_CONFIG_NODE="true"

#export MAVEN_OPTS=-Xmx8192m
#export MAVEN_OPTS=-Xmx16384m
export MAVEN_OPTS=-Xmx24576m
#export MAVEN_OPTS=-Xmx32768m
	

clear
echo "Running Experiment $EXPT, Config $CONF"

echo "Running IPOMCP Simulator" 
echo "With params: Config - $CONF Gamma - $GAMMA Epsilone - $EPSILON Max Horizon - $MAXHORIZONS Stages - $MAXSTAGES Trials - $MAXTRIALS Time Bound in Mili Second - $TIME_BOUND Experiment - $EXPT Sampling Error - $SAMPLING_ERROR_BOUND Alpha - $ALPHA Particle Count - $PARTICLE_COUNT Bandit Constant - $BANDIT_CONSTANT"

echo "PRINT TREE TRIAL"
mvn exec:java -Dexec.mainClass="simulators.IPOMCPSimulator" -Dexec.args="$CONF $GAMMA $EPSILON $MAXHORIZONS $MAXSTAGES $ITERATIVE_TRIALS $TIME_BOUND $EXPT $SAMPLING_ERROR_BOUND $ALPHA $PARTICLE_COUNT $BANDIT_CONSTANT $IS_FIRE_RANDOM $IS_SUPP_RANDOM $IS_AVGQ_ANODE $IS_OPEN_SUPP $IS_SINGLE_CONFIG_NODE"

IPOMCP_SCRIPT="echo \"RUN IPOMCP:\""
for ((t=1;t<=$SETSOFTRIAL;t++)); do
     IPOMCP_SCRIPT="$IPOMCP_SCRIPT & mvn exec:java -Dexec.mainClass=\"simulators.IPOMCPSimulator\" -Dexec.args=\"$CONF $GAMMA $EPSILON $MAXHORIZONS $MAXSTAGES $ITERATIVE_TRIALS $TIME_BOUND $EXPT $SAMPLING_ERROR_BOUND $ALPHA $PARTICLE_COUNT $BANDIT_CONSTANT $IS_FIRE_RANDOM $IS_SUPP_RANDOM $t $IS_AVGQ_ANODE $IS_OPEN_SUPP $IS_SINGLE_CONFIG_NODE\""
done
echo $IPOMCP_SCRIPT
eval $IPOMCP_SCRIPT


done

